if(CONFIG_HAS_CC13X2_CC26X2_SDK OR CONFIG_HAS_CC13X2X7_CC26X2X7_SDK OR CONFIG_HAS_CC3220SDK OR CONFIG_HAS_MSP432P4XXSDK)
add_subdirectory(simplelink)
endif()
if(CONFIG_HAS_CC23X0_SDK)
add_subdirectory(simplelink_lpf3)
endif()
if(CONFIG_HAS_TIVAWARE)
add_subdirectory(tivaware)
endif()
if(CONFIG_HAS_MSPM0_SDK)
add_subdirectory(mspm0)
endif()
